scripts/installer: snapshot from AIX_Clusterware_shutdown delivery (2015-11-18)

diff --git a/scripts/installer/common/ipp-status b/scripts/installer/common/ipp-status
--- a/scripts/installer/common/ipp-status
+++ b/scripts/installer/common/ipp-status
@@ -1,11 +1,18 @@
 #!/bin/sh
 
 #
-# Global vaiables
+# Global variables
 #
 upsc="/usr/local/ups/bin/upsc"
 upsmon_conf="/usr/local/ups/etc/upsmon.conf"
+CONFIG="/usr/local/ups/etc/ipp.conf"
 
+SHUTDOWN_TIMER=-1
+
+# Include IPP ipp.conf (may overwrite the above default values!)
+if test -f $CONFIG ; then
+	. $CONFIG
+fi
 
 #
 # We need capable awk
@@ -66,9 +73,11 @@ get_pwr_value() {
 #
 overall_status() {
 	devices_info="$1"
+	onbattery_sdtimer="$2"	# set to yes to trigger a shutdown timer
+				# when UPS are on battery
 
 	# Get non-low battery UPSes (still protecting the system)
-	protectors=`echo "$devices_info" | $awk -F: '
+	protectors=`echo "$devices_info" | $awk -v ob_sdtimer="${onbattery_sdtimer}" -F: '
 	{
 		status = $2;
 
@@ -84,21 +93,56 @@ overall_status() {
 		else if (match(status, /^OB LB/))
 			;
 
-		# Other on-battery states are OK
+		# - NOK when onbattery_sdtimer = yes
+		# - OK otherwise
 		else if (match(status, /^OB/))
+			if (match(ob_sdtimer, /^yes/))
+				;
+			else
+				print $1;
+	}
+	' | sort | uniq`
+
+	protectors_unknown=`echo "$devices_info" | $awk -F: '
+	{
+		status = $2;
+
+		# Do not cause immediate shutdown if UPS is not accessible
+		# (driver or connection failure) when onbattery_sdtimer = yes
+		if (status == "")
+			print $1;
+		if (match(status, /WAIT/))
 			print $1;
 	}
-	'`
+	' | sort | uniq`
 
 	# Get total powervalue of protecting UPSes
 	protectors_pwr_value=0
+	protectors_unknown_pwr_value=0
+	not_protectors=0
 
 	for ups in $protectors; do
 		pwr_value=`get_pwr_value "$ups"`
 
 		test -n "$pwr_value" || pwr_value=1
 
-		protectors_pwr_value=`expr $protectors_pwr_value + $pwr_value`
+		if test "$pwr_value" -eq 0 ; then
+			not_protectors=`expr $not_protectors + 1`
+		else
+			protectors_pwr_value=`expr $protectors_pwr_value + $pwr_value`
+		fi
+	done
+
+	for ups in $protectors_unknown; do
+		pwr_value=`get_pwr_value "$ups"`
+
+		test -n "$pwr_value" || pwr_value=1
+
+		if test "$pwr_value" -eq 0 ; then
+			not_protectors=`expr $not_protectors + 1`
+		else
+			protectors_unknown_pwr_value=`expr $protectors_unknown_pwr_value + $pwr_value`
+		fi
 	done
 
 	# Resolve system protection status
@@ -108,7 +152,13 @@ overall_status() {
 
 	test -n "$min_supplies" || min_supplies=1
 
-	if test $protectors_pwr_value -lt $min_supplies; then
+	min_supplies_eff="$min_supplies"
+	if test "$protectors_unknown_pwr_value" -gt 0; then
+		min_supplies_eff=`expr $min_supplies - $protectors_unknown_pwr_value`
+		test "$min_supplies_eff" -ge 0 || min_supplies_eff=0
+	fi
+
+	if test $protectors_pwr_value -lt $min_supplies_eff; then
 		overall_status_str="unprotected"
 	fi
 
@@ -126,11 +176,25 @@ overall_status() {
 		cat <<HERE
 Your system IS NOT PROTECTED
 
-Only $protectors_pwr_value power backups are available (out of $min_supplies required)
+Only $protectors_pwr_value power backups are available (out of $min_supplies required with $protectors_unknown_pwr_value ignored)
 HERE
 	else
-		echo "Your system is protected"
+		echo "Your system is protected ($protectors_pwr_value power backups out of $min_supplies required with $protectors_unknown_pwr_value ignored are available)"
 	fi
+
+	if test "$not_protectors" -gt 0 2>/dev/null ; then
+		echo "Also, $not_protectors device(s) that do not feed this host are known and monitored"
+	fi
+
+	case "$onbattery_sdtimer" in
+	[Yy][Ee][Ss])
+		if test "$min_supplies_eff" != "$min_supplies" ; then
+			echo "WARNING: Some UPSes are not available, but we ignored them since onbattery_sdtimer=yes" >&2
+		fi ;;
+	esac
+
+	test "$overall_status_str" = "unprotected" && return 1
+	return 0
 }
 
 
@@ -213,6 +277,8 @@ HERE
 
 		# Resolve basic status
 		if (status == "")
+			status_str = "unknown";
+		else if (match(status, /WAIT/))
 			status_str = "unknown";
 		else if (match(status, /^OL BYPASS/))
 			status_str = "on bypass";
@@ -352,12 +418,17 @@ shift
 # Main
 #
 
+onbattery_sdtimer="no"
+if test $SHUTDOWN_TIMER -gt -1 2>/dev/null ; then
+	onbattery_sdtimer="yes"
+fi
+
 # Get devices info
 devices_info=`get_devices_info`
 
 # Overall status
 if test "$overall_status_enabled" = "yes"; then
-	overall_status "$devices_info"
+	overall_status "$devices_info" "$onbattery_sdtimer"
 fi
 
 # Devices status
diff --git a/scripts/installer/uninstall-ipp b/scripts/installer/uninstall-ipp
--- a/scripts/installer/uninstall-ipp
+++ b/scripts/installer/uninstall-ipp
@@ -1,16 +1,18 @@
 #!/bin/sh
 #	uninstall.sh
-#	Copyright (c) 2013, by Eaton (R) Corporation. All rights reserved.
+#	Copyright (c) 2013-2015, by Eaton (R) Corporation. All rights reserved.
 #	A shell script which installs IPP - Unix
 #	It installs the native package then runs NUT configuration tools
 #	to create an initial configuration and finally run the service.
-PATH=$PATH:/bin:/usr/bin; export PATH
+#
+PATH="$PATH:/bin:/usr/bin:/sbin:/usr/sbin"
+export PATH
 
 
 NUT_PACKAGE_SOLARI="NUT_solaris_sparc_package2.6.5.local"
 NUT_PACKAGE_SOLINT="NUT_solaris_i386_package2.6.5.local"
 
-cd `dirname $0`
+cd "`dirname "$0"`"
 
 #configuration data
 C_MODE="standalone"
@@ -20,7 +22,7 @@ C_DEVICE=""
 C_PASSWORD=""
 
 # /dev/tty user & group used on the supported systems
-case `uname -s` in
+case "`uname -s`" in
 	"SunOS")
 		TTY_OWNER="root:root"
 		;;
@@ -41,10 +43,10 @@ DO_UNINSTALL=""
 ADMIN_FILE="/tmp/ipp_admin_file"
 
 UNINSTALL_TMP="/tmp"
-LOG_FILE=$UNINSTALL_TMP/uninstall.log
+LOG_FILE="$UNINSTALL_TMP/uninstall.log"
 
 get_parameters() {
-	case $1 in
+	case "$1" in
 	English)
 		lang=EN
 		;;
@@ -52,27 +54,26 @@ get_parameters() {
 #		lang=JP
 #		;;
 	SOLARI)
-		SYSTEM=$1
+		SYSTEM="$1"
 		;;
 	SOLINT)
-		SYSTEM=$1
+		SYSTEM="$1"
 		;;
 	HPUX)
-		SYSTEM=$1
+		SYSTEM="$1"
 		;;
 	AIX)
-		SYSTEM=$1
+		SYSTEM="$1"
 		;;
 	DO_UNINSTALL)
 		DO_UNINSTALL="OK"
 		;;
 	esac
-	
 }
 
 check_locale_language() {
 	set `locale` >/dev/null 2>&1
-	case $1 in
+	case "$1" in
 	LANG=en_US)
 		lang=EN
 		;;
@@ -84,11 +85,11 @@ check_locale_language() {
 
 compute_SYSTEM () {
 	set `uname -a`
-	case $1 in
+	case "$1" in
 	SunOS)
-		case $3 in
+		case "$3" in
 		5.*)
-			case $5 in
+			case "$5" in
 			i86pc)
 				SYSTEM=SOLINT
 				;;
@@ -106,7 +107,7 @@ compute_SYSTEM () {
 		SYSTEM=HPUX
 		;;
 	AIX)
-		case $4 in
+		case "$4" in
 		6)
 			SYSTEM=AIX
 			;;
@@ -127,7 +128,7 @@ compute_SYSTEM () {
 }
 
 compute_system () {
-	case $SYSTEM in
+	case "$SYSTEM" in
 	SOLINT)
 		system=solint
 		;;
@@ -142,31 +143,31 @@ compute_system () {
 		;;
 	*)
 		echo
-		echo "Please specify your system like, \"./install.sh <SYSTEM>\""
-		echo Valid systems are SOLINT SOLARI HPUX AIX
+		echo "Please specify your system like './install.sh <SYSTEM>'"
+		echo "Valid systems are SOLINT SOLARI HPUX AIX"
 		echo
-		exit
+		exit 1
 		;;
 	esac
 }
 
 create_admin_file () {
-        echo basedir=default > $ADMIN_FILE
-        echo runlevel=quit >> $ADMIN_FILE
-        echo conflict=nocheck >> $ADMIN_FILE
-        echo setuid=nocheck >> $ADMIN_FILE
-        echo action=nocheck >> $ADMIN_FILE
-        echo partial=nocheck >> $ADMIN_FILE
-        echo instance=unique >> $ADMIN_FILE
-        echo idepend=quit >> $ADMIN_FILE
-        echo rdepend=quit >> $ADMIN_FILE
-        echo space=quit >> $ADMIN_FILE
+        echo basedir=default > "$ADMIN_FILE"
+        echo runlevel=quit >> "$ADMIN_FILE"
+        echo conflict=nocheck >> "$ADMIN_FILE"
+        echo setuid=nocheck >> "$ADMIN_FILE"
+        echo action=nocheck >> "$ADMIN_FILE"
+        echo partial=nocheck >> "$ADMIN_FILE"
+        echo instance=unique >> "$ADMIN_FILE"
+        echo idepend=quit >> "$ADMIN_FILE"
+        echo rdepend=quit >> "$ADMIN_FILE"
+        echo space=quit >> "$ADMIN_FILE"
 }
 
 restore_ttys () {
 	for tty in `find /dev/tty* -user ipp`; do
-		chown $TTY_OWNER $tty
-		chmod 622 $tty
+		chown "$TTY_OWNER" "$tty"
+		chmod 622 "$tty"
 	done
 }
 
@@ -183,29 +184,16 @@ killall_nut () {
 }
 
 uninstall_files () {
-	echo 
-	echo Uninstalling IPP - Unix | tee -a $LOG_FILE
-	echo 
+	rm -f "$LOG_FILE" > /dev/null 2>&1
+	touch "$LOG_FILE"
 
-	rm $LOG_FILE > /dev/null 2>&1
-	touch $LOG_FILE
+	echo
+	echo "`date`: Uninstalling IPP - Unix" | tee -a "$LOG_FILE"
+	echo
 
-	rm $instpath/bin/uninstall* >> $LOG_FILE 2>&1
-
-	rm $instpath/init >> $LOG_FILE 2>&1
-	rm $instpath/shutdown >> $LOG_FILE 2>&1
-
-        rm $instpath/bin/ipp-notifier.sh >> $LOG_FILE 2>&1
-        rm $instpath/bin/ipp-status >> $LOG_FILE 2>&1
-
-	rm $instpath/share/string.sh >> $LOG_FILE 2>&1
-	rm $instpath/share/install.res >> $LOG_FILE 2>&1
-
-	rm -Rf $instpath/lib >> $LOG_FILE 2>&1
-
-	case $system in
+	case "$system" in
 	solari)
-		/etc/init.d/nut stop >> $LOG_FILE 2>&1
+		/etc/init.d/nut stop >> "$LOG_FILE" 2>&1
 
 		sleep 5
 		killall_nut
@@ -213,12 +201,12 @@ uninstall_files () {
 		create_admin_file
 		restore_ttys
 
-		pkgrm -n -a $ADMIN_FILE NUT >> $LOG_FILE 2>&1
-		rm -f $ADMIN_FILE
+		pkgrm -n -a "$ADMIN_FILE" NUT >> "$LOG_FILE" 2>&1
+		rm -f "$ADMIN_FILE"
 		#uninstall additional libraries
 	;;
 	solint)
-		/etc/init.d/nut stop >> $LOG_FILE 2>&1
+		/etc/init.d/nut stop >> "$LOG_FILE" 2>&1
 
 		sleep 5
 		killall_nut
@@ -226,43 +214,57 @@ uninstall_files () {
 		create_admin_file
 		restore_ttys
 
-		pkgrm -n -a $ADMIN_FILE NUT >> $LOG_FILE 2>&1
-		rm -f $ADMIN_FILE
+		pkgrm -n -a "$ADMIN_FILE" NUT >> "$LOG_FILE" 2>&1
+		rm -f "$ADMIN_FILE"
 		#uninstall additional libraries
 
 	;;
 	hpux)
-		/sbin/init.d/nut-drvctl stop >> $LOG_FILE 2>&1
-                /sbin/init.d/nut-upsd stop >> $LOG_FILE 2>&1
-                /sbin/init.d/nut-upsmon stop >> $LOG_FILE 2>&1
+		/sbin/init.d/nut-drvctl stop >> "$LOG_FILE" 2>&1
+		/sbin/init.d/nut-upsd stop >> "$LOG_FILE" 2>&1
+		/sbin/init.d/nut-upsmon stop >> "$LOG_FILE" 2>&1
 
 		sleep 5
 		killall_nut
 
 		restore_ttys
 
-		swremove NUT >> $LOG_FILE 2>&1
+		swremove NUT >> "$LOG_FILE" 2>&1
 		#uninstall additional libraries
 	;;
 	aix)
-		/etc/rc.d/init.d/ups stop >> $LOG_FILE 2>&1
+		/etc/rc.d/init.d/ups stop >> "$LOG_FILE" 2>&1
 
 		sleep 5
 		killall_nut
 
 		restore_ttys
 
-		rpm -e nut >> $LOG_FILE 2>&1
-		rpm -e nut-client >> $LOG_FILE 2>&1
+		rpm -e nut >> "$LOG_FILE" 2>&1
+		rpm -e nut-client >> "$LOG_FILE" 2>&1
 		#uninstall additional libraries
 	;;
 
 	*)
-		echo Installation error, please see uninstall.log.
+		echo "Installation error, please see $LOG_FILE."
 		exit 1
 	;;
 	esac
 
+	rm -f "$instpath/bin/uninstall"* >> "$LOG_FILE" 2>&1
+
+	rm -f "$instpath/init" >> "$LOG_FILE" 2>&1
+	rm -f "$instpath/shutdown" >> "$LOG_FILE" 2>&1
+	rm -f "$instpath/sbin/ipp-os-shutdown" >> "$LOG_FILE" 2>&1
+	rm -f "$instpath/sbin/AIX_Clusterware_shutdown" >> "$LOG_FILE" 2>&1
+
+	rm -f "$instpath/bin/ipp-notifier.sh" >> "$LOG_FILE" 2>&1
+	rm -f "$instpath/bin/ipp-status" >> "$LOG_FILE" 2>&1
+
+	rm -f "$instpath/share/string.sh" >> "$LOG_FILE" 2>&1
+	rm -f "$instpath/share/install.res" >> "$LOG_FILE" 2>&1
+
+	rm -Rf "$instpath/lib" >> "$LOG_FILE" 2>&1
 }
 
 remove_profile_settings () {
@@ -292,8 +294,8 @@ remove_profile_settings () {
 
 main () {
 # Setup some globals
-instpath=/usr/local/ups
-ret=TRUE;
+	instpath=/usr/local/ups
+	ret=TRUE
 
 # Must check parameters
 	SYSTEM=""
@@ -311,29 +313,32 @@ ret=TRUE;
 		get_parameters $3
 	fi
 
-
 	if [ ! "$DO_UNINSTALL" = "OK" ];then
-		cp -f $instpath/bin/uninstall-ipp $UNINSTALL_TMP
-		chmod 744 $UNINSTALL_TMP/uninstall-ipp
-		exec $UNINSTALL_TMP/uninstall-ipp DO_UNINSTALL $1 $2 $3
+		cp -f "$instpath/bin/uninstall-ipp" "$UNINSTALL_TMP"
+		chmod 744 "$UNINSTALL_TMP/uninstall-ipp"
+		exec "$UNINSTALL_TMP/uninstall-ipp" DO_UNINSTALL $1 $2 $3
 		exit
 	fi
 
 	compute_SYSTEM
 
-# Get language locale 
+# Get language locale
 	if [ "$lang" = "" ]; then
 		check_locale_language
 		if [ -z "$lang" ]; then
 			lang=EN
 		fi
-	fi 
+	fi
 
-who=`whoami`
-if [ "$who" != 'root' ]; then
-        echo You must be root to uninstall IPP - Unix.
-        exit 1;
-fi
+	who="`whoami 2>/dev/null`"
+	if [ "$who" != 'root' ]; then
+		#work around in case no whoami is present
+		who="`id -u 2>/dev/null`"
+		if [ "$who" != '0' ]; then
+			echo "You must be root to uninstall IPP - Unix."
+			exit 1
+		fi
+	fi
 
 	uninstall_files
 	remove_profile_settings
