scripts/installer/*: use configure-script or otherwise detected functional GREP/EGREP if possible [#3099]
Signed-off-by: Jim Klimov <jimklimov+nut@gmail.com>

diff --git a/scripts/installer/common/ipp-os-shutdown b/scripts/installer/common/ipp-os-shutdown
--- a/scripts/installer/common/ipp-os-shutdown
+++ b/scripts/installer/common/ipp-os-shutdown
@@ -52,6 +52,10 @@ fi >&2
 PATH="$NUT_DIR/xbin:$NUT_DIR/sbin:$NUT_DIR/bin:$PATH"
 export PATH
 
+# tools
+[ -n "${GREP}" ] || { GREP="`command -v grep`" && [ x"${GREP}" != x ] || { echo "$0: FAILED to locate GREP tool" >&2 ; exit 1 ; } ; }
+[ -n "${EGREP}" ] || { if ( [ x"`echo a | $GREP -E '(a|b)'`" = xa ] ) 2>/dev/null ; then EGREP="$GREP -E" ; else EGREP="`command -v egrep`" ; fi && [ x"${EGREP}" != x ] || { echo "$0: FAILED to locate EGREP tool" >&2 ; exit 1 ; } ; }
+
 # Search for binaries under current PATH normally, no hardcoding
 NUT_UPSC="upsc"
 NUT_UPSCMD="upscmd"
@@ -187,8 +191,8 @@ check_pid() {
 	# Returns: PID in $1 is running = 0; not running = 1; syntax errors = 2
 	[ -n "$1" ] && [ "$1" -gt 0 ] || return 2
 	[ -d "/proc/$1" ] && return 0
-	( (ps -ef || ps -xawwu ) | grep -v grep | egrep "`basename \"$0\"`|shutdown" | \
-		awk '{print $2}' | grep -w "$1" ) 2>/dev/null && return 0
+	( (ps -ef || ps -xawwu ) | ${GREP} -v grep | ${EGREP} "`basename \"$0\"`|shutdown" | \
+		awk '{print $2}' | ${GREP} -w "$1" ) 2>/dev/null && return 0
 	return 1
 }
 
@@ -294,7 +298,7 @@ case "$RES" in
 esac
 
 if [ -f "$CONFIG_UPSMON" ]; then
-	_VAR="`egrep '^[ \t]*POWERDOWNFLAG ' \"$CONFIG_UPSMON\" | sed 's,^[ \t]*POWERDOWNFLAG ,,'`"
+	_VAR="`${EGREP} '^[ \t]*POWERDOWNFLAG ' \"$CONFIG_UPSMON\" | sed 's,^[ \t]*POWERDOWNFLAG ,,'`"
 	_VAR="$(echo "$_VAR" | sed -e 's,^"\(.*\)"$,\1,g' -e "s,^\'\(.*\)\'$,\1,g")"
 	if [ $? = 0 ] && [ -n "$_VAR" ]; then
 		POWERDOWNFLAG="$_VAR"
diff --git a/scripts/installer/common/ipp-status b/scripts/installer/common/ipp-status
--- a/scripts/installer/common/ipp-status
+++ b/scripts/installer/common/ipp-status
@@ -33,6 +33,10 @@ CONFIG_IPP="$NUT_CFG_DIR/ipp.conf"
 PATH="$NUT_DIR/xbin:$NUT_DIR/sbin:$NUT_DIR/bin:$PATH"
 export PATH
 
+# tools
+[ -n "${GREP}" ] || { GREP="`command -v grep`" && [ x"${GREP}" != x ] || { echo "$0: FAILED to locate GREP tool" >&2 ; exit 1 ; } ; }
+[ -n "${EGREP}" ] || { if ( [ x"`echo a | $GREP -E '(a|b)'`" = xa ] ) 2>/dev/null ; then EGREP="$GREP -E" ; else EGREP="`command -v egrep`" ; fi && [ x"${EGREP}" != x ] || { echo "$0: FAILED to locate EGREP tool" >&2 ; exit 1 ; } ; }
+
 # Search for binaries under current PATH normally, no hardcoding
 NUT_UPSC="upsc"
 #NUT_UPSC="$NUT_DIR/xbin/upsc"
@@ -76,8 +80,8 @@ get_devices_info() {
 		status="`$NUT_UPSC \"$dev\" ups.status 2>/dev/null`"
 		runtime="`$NUT_UPSC \"$dev\" battery.runtime 2>/dev/null`"
 		batterypct="`$NUT_UPSC \"$dev\" battery.charge 2>/dev/null`"
-		supplies="`get_pwr_value \"$dev\" | egrep '^[0-9]*$'`"
-		upsmon_ms="`get_ms_value \"$dev\" | egrep 'master|slave'`"
+		supplies="`get_pwr_value \"$dev\" | ${EGREP} '^[0-9]*$'`"
+		upsmon_ms="`get_ms_value \"$dev\" | ${EGREP} 'master|slave'`"
 
 		echo "$dev:$status:$runtime:$batterypct:$supplies:$upsmon_ms"
 	done
