nut-driver-enumerator.sh.in : avoid sub-shelling and varname clash in smf_setSavedUniq() and smf_setSavedMD5()

diff --git a/scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in b/scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
--- a/scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
+++ b/scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
@@ -736,47 +736,47 @@ smf_getSavedDeviceName() {
     # Note: lookups for GLOBAL cause each service instance to show up
     /usr/bin/svcprop -p "$PG/$PROP" "$TARGET_FMRI" 2>/dev/null | head -1 | awk '{print $NF}'
 }
-smf_setSavedUniq() (
+smf_setSavedUniq() {
     # Save data value $5 of type $4 into service FMRI $1
     # under (scrapped and) newly created property group $2
     # and property name $3
-    _TARGET_FMRI="$1"
-    _PG="$2"
-    _PROP="$3"
-    _TYPE="$4"
-    case "${_TYPE}" in
+    __TARGET_FMRI="$1"
+    __PG="$2"
+    __PROP="$3"
+    __TYPE="$4"
+    case "${__TYPE}" in
         *:) ;;
-        *) _TYPE="${_TYPE}:" ;;
+        *) __TYPE="${__TYPE}:" ;;
     esac
-    _VAL="$5"
-    /usr/sbin/svccfg -s "${_TARGET_FMRI}" delprop "${_PG}" 2>/dev/null || true
-    /usr/sbin/svccfg -s "${_TARGET_FMRI}" addpg "${_PG}" application && \
-    /usr/sbin/svccfg -s "${_TARGET_FMRI}" setprop "${_PG}/${_PROP}" = "${_TYPE}" "${_VAL}"
-    [ $? = 0 ] && echo "OK" || { echo "FAILED to stash the service property ${_PG}/${_PROP}">&2 ; return 1 ; }
+    __VAL="$5"
+    /usr/sbin/svccfg -s "${__TARGET_FMRI}" delprop "${__PG}" 2>/dev/null || true
+    /usr/sbin/svccfg -s "${__TARGET_FMRI}" addpg "${__PG}" application && \
+    /usr/sbin/svccfg -s "${__TARGET_FMRI}" setprop "${__PG}/${__PROP}" = "${__TYPE}" "${__VAL}"
+    [ $? = 0 ] && echo "OK" || { echo "FAILED to stash the service property ${__PG}/${__PROP}">&2 ; return 1 ; }
 
-    case "${_TARGET_FMRI}" in
+    case "${__TARGET_FMRI}" in
         svc:/*:*) ;; # A service instance by full FMRI, refresh
         svc:/*/nut-driver|nut-driver) return 0 ;; # A base non-instance service item for nut-driver (known multi-instance only)
         svc:/*) ;; # A base non-instance service item (not nut-driver)
         *:*) ;; # A service instance by short FMRI, refresh
         *) ;; # A base non-instance service item (not nut-driver)
     esac
-    /usr/sbin/svcadm refresh "${TARGET_FMRI}" || return
-)
-smf_setSavedMD5() (
+    /usr/sbin/svcadm refresh "${__TARGET_FMRI}" || return
+}
+smf_setSavedMD5() {
     # Save checksum value $2 into service instance $1
-    PG="nut-driver-enumerator-generated-checksum"
-    PROP="SECTION_CHECKSUM"
+    _PG="nut-driver-enumerator-generated-checksum"
+    _PROP="SECTION_CHECKSUM"
 
     if [ -n "$1" ]; then
-        TARGET_FMRI="nut-driver:$1"
+        _TARGET_FMRI="nut-driver:$1"
     else
         # Global section
-        TARGET_FMRI="nut-driver"
-        PROP="SECTION_CHECKSUM_GLOBAL"
+        _TARGET_FMRI="nut-driver"
+        _PROP="SECTION_CHECKSUM_GLOBAL"
     fi
-    smf_setSavedUniq "$TARGET_FMRI" "$PG" "$PROP" astring "$2"
-)
+    smf_setSavedUniq "${_TARGET_FMRI}" "${_PG}" "${_PROP}" astring "$2"
+}
 smf_setSavedDeviceName() {
     [ -n "$1" ] || return # No-op for global section
     smf_setSavedUniq "nut-driver:$1" "nut-driver-enumerator-generated-devicename" "DEVICE" astring "$2"
