scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in: consider two empty UPS lists (conf and svc) as a valid situation (nothing to reconcile yet) [#2178]
Signed-off-by: Jim Klimov <jimklimov+nut@gmail.com>

diff --git a/scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in b/scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
--- a/scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
+++ b/scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
@@ -1008,8 +1008,8 @@ nut_driver_enumerator_main() {
     RESTART_ALL=no
     upssvcconf_checksum_unchanged "" || { echo "`date -u` : Detected changes in global section of '$UPSCONF', will restart all drivers"; RESTART_ALL=yes; }
 
-    # Quickly exit if there's nothing to do; note the lists are pre-sorted
-    # Otherwise a non-zero exit will be done below
+    # Quickly exit if there's nothing to do (both lists empty or equal); note
+    # the lists are pre-sorted. Otherwise a non-zero exit will be done below.
     # Note: We implement testing in detail whether section definitions were
     # changed since last run, as a first step before checking that name
     # lists are still equivalent, because we need to always have the result
@@ -1017,9 +1017,11 @@ nut_driver_enumerator_main() {
     # while the check for no new device section definitions is just boolean.
     # We can only exit quickly if both there are no changed sections and no
     # new or removed sections since last run.
-    NEW_CHECKSUM="`upslist_checksums_unchanged "$UPSLIST_FILE" "$UPSLIST_SVCS"`" \
-    && [ -z "$NEW_CHECKSUM" ] \
-    && upslist_equals "$UPSLIST_FILE" "$UPSLIST_SVCS" \
+    ( [ -z "$UPSLIST_FILE" -a -z "$UPSLIST_SVCS" ] || ( \
+        NEW_CHECKSUM="`upslist_checksums_unchanged "$UPSLIST_FILE" "$UPSLIST_SVCS"`" \
+        && [ -z "$NEW_CHECKSUM" ] \
+        && upslist_equals "$UPSLIST_FILE" "$UPSLIST_SVCS" \
+    ) ) \
     && if [ -z "$DAEMON_SLEEP" -o "${VERBOSE_LOOP}" = yes ] ; then \
         echo "`date -u` : OK: No changes to reconcile between ${SERVICE_FRAMEWORK} service instances and device configurations in '$UPSCONF'" ; \
        fi \
