upsdrvsvcctl.in nut-driver-enumerator.sh.in : Add a way to show configs per device

diff --git a/scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in b/scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
--- a/scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
+++ b/scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
@@ -219,6 +219,40 @@ $_DEV = $_SVC" ; }
     [ "`echo "$1" | wc -l`" = "`echo "$_TMP_DEV_SVC" | wc -l`" ]
 }
 
+upsconf_getSection() {
+    # "$1" = name of ups.conf section to display in whole
+    [ -n "$1" ] || return $?
+    CURR_SECTION=""
+    RES=1
+
+    if [ -n "$UPSCONF" ] && [ -f "$UPSCONF" ] && [ -r "$UPSCONF" ]; then
+        [ ! -s "$UPSCONF" ] \
+        && echo "WARNING: The '$UPSCONF' file exists but is empty" >&2 \
+        && return 3
+    else
+        echo "FATAL: The '$UPSCONF' file does not exist or is not readable" >&2
+        return 2
+    fi
+
+    while read LINE ; do
+        case "$LINE" in
+            \["$1"\]) CURR_SECTION="$1" ; echo "$LINE"; RES=0 ;;
+            \[*\])
+                [ "$CURR_SECTION" = "$1" ] && break
+                CURR_SECTION="other"
+                ;;
+            "") ;;
+            *)  if [ "$CURR_SECTION" = "$1" ]; then
+                    echo "$LINE"
+                fi
+                ;;
+        esac
+    done < "$UPSCONF"
+
+    [ "$RES" = 0 ] || echo "ERROR: Section [$1] was not found in the '$UPSCONF' file" >&2
+    return $RES
+}
+
 upsconf_getValue() {
     # "$1" = name of ups.conf section; $2 = name of config key; echo the value
     [ -n "$1" ] || return $?
@@ -591,6 +625,9 @@ $0 --get-device-for-service SVC
 $0 --list-services-for-devices
         Print a TAB-separated list of service units and corresponding
         NUT device names which each such unit wraps
+$0 --show-config DEV
+$0 --show-device-config DEV
+        Show configuration block of the specified NUT device
 EOF
 }
 
@@ -717,6 +754,12 @@ while [ $# -gt 0 ]; do
                 FINAL_RES=1
             done
             exit $FINAL_RES
+            ;;
+        --show-config|--show-device-config)
+            [ -z "$2" ] && echo "Device name argument required" >&2 && exit 1
+            DEV="$2"
+            upsconf_getSection "$DEV"
+            exit $?
             ;;
         *) echo "Unrecognized argument: $1" >&2 ; exit 1 ;;
     esac
diff --git a/scripts/upsdrvsvcctl/upsdrvsvcctl.in b/scripts/upsdrvsvcctl/upsdrvsvcctl.in
--- a/scripts/upsdrvsvcctl/upsdrvsvcctl.in
+++ b/scripts/upsdrvsvcctl/upsdrvsvcctl.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright (C) 2016-2017 Eaton
+# Copyright (C) 2016-2018 Eaton
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -78,6 +78,7 @@ usage: $0 [OPTIONS] resync
   list          	call $ENUMERATOR
                 	to list the mapping of service instances to device sections
   list <ups>    	(optionally return the service instance name for one device)
+  show-config <ups>     output config section from ups.conf for device <ups>
 EOF
 }
 
@@ -94,6 +95,13 @@ while [ $# -gt 0 ]; do
                 eval $ENUMERATOR --get-service-for-device "$2" ; exit $?
             else
                 eval $ENUMERATOR --list-services-for-devices ; exit $?
+            fi
+            ;;
+        show-config)
+            if [ -n "$2" ] ; then
+                eval $ENUMERATOR --show-device-config "$2" ; exit $?
+            else
+                echo "ERROR: Argument required" >&2; exit 1
             fi
             ;;
         start|stop)
