scripts/systemd/nutshutdown.in: make it useful for NUT clients (which shut down and may want to avoid power races)
Signed-off-by: Jim Klimov <jimklimov+nut@gmail.com>

diff --git a/scripts/systemd/nutshutdown.in b/scripts/systemd/nutshutdown.in
--- a/scripts/systemd/nutshutdown.in
+++ b/scripts/systemd/nutshutdown.in
@@ -32,9 +32,14 @@ POWEROFF_QUIET="`/bin/sed -ne 's#^ *POWEROFF_QUIET= *\(.*\)$#\1#p' @CONFPATH@/nu
 && [ x"${POWEROFF_QUIET-}" = xtrue ] \
 || POWEROFF_QUIET="false"
 
-[ -x "@SBINDIR@/upsmon" ] && [ -x "@SBINDIR@/upsdrvctl" ] || {
-    $POWEROFF_QUIET || echo "$0: SKIP: could not locate '@SBINDIR@/upsmon' and/or '@SBINDIR@/upsdrvctl'" >&2
+[ -x "@SBINDIR@/upsmon" ] || {
+    $POWEROFF_QUIET || echo "$0: SKIP: could not locate '@SBINDIR@/upsmon''" >&2
     exit 1
+}
+
+# Will at most run the optional power-race avoidance sleep part
+[ -x "@SBINDIR@/upsdrvctl" ] || {
+    $POWEROFF_QUIET || echo "$0: WARNING: could not locate '@SBINDIR@/upsdrvctl' - will not command any UPS devices to shut down" >&2
 }
 
 if @SBINDIR@/upsmon -K >/dev/null 2>&1; then
@@ -43,8 +48,10 @@ if @SBINDIR@/upsmon -K >/dev/null 2>&1; then
     # so not necessarily a non-negative integer)
     wait_delay="`/bin/sed -ne 's#^ *POWEROFF_WAIT= *\(.*\)$#\1#p' @CONFPATH@/nut.conf`" || wait_delay=""
 
-    $POWEROFF_QUIET || echo "$0: Commanding UPSes (if any) to shutdown" >&2
-    @SBINDIR@/upsdrvctl shutdown
+    if [ -x "@SBINDIR@/upsdrvctl" ] ; then
+        $POWEROFF_QUIET || echo "$0: Commanding UPSes (if any) to shutdown" >&2
+        @SBINDIR@/upsdrvctl shutdown || echo "$0: Something failed about UPS shutdown commands" >&2
+    fi
 
     if [ -n "$wait_delay" ] ; then
         # Avoid the power-race condition (if wall power returned
