post 2.2.2 sync with Testing
Fossil-ID: SVN r1483

diff --git a/packaging/debian/nut-hal-drivers.preinst b/packaging/debian/nut-hal-drivers.preinst
--- a/packaging/debian/nut-hal-drivers.preinst
+++ b/packaging/debian/nut-hal-drivers.preinst
@@ -3,40 +3,32 @@
 # source the debconf library
 . /usr/share/debconf/confmodule
 
-check_hal_in_nut_group() {
-	if [ -z "`getent group nut | grep haldaemon`" ]; then
-		adduser --quiet haldaemon nut
-	fi
-}
-
 check_and_create_group() {
-	if [ ! "`getent group nut`" ]; then
-		addgroup --quiet --system nut
-	fi
+        if [ -z `getent group nut` ]; then
+                addgroup --quiet --system nut
+#       else
+#               printf "error: user \"nut\" already exists... see /usr/share/doc/nut/README.Debian\n"  &&  exit 1
+        fi
 }
 
 check_and_create_user() {
-	if [ ! "`getent passwd nut`" ]; then
-		adduser --quiet --system --ingroup nut --home /var/lib/nut --no-create-home nut
-	fi
+        if [ -z `getent passwd nut` ]; then
+                adduser --quiet --system --ingroup nut --home /var/lib/nut --no-create-home nut
+#       else
+#               printf "error: user \"nut\" already exists... see /usr/share/doc/nut/README.Debian\n"  &&  exit 1
+        fi
 }
 
 case "$1" in
 
-  install)
+  install|upgrade)
     # Check for existing nut system account, and create it if needed
     check_and_create_group
     check_and_create_user
     # Add the haldaemon user to the nut group
-    check_hal_in_nut_group
-    ;;
-
-  upgrade)
-    # Check for existing nut system account, and create it if needed
-    check_and_create_group
-    check_and_create_user
-    # Add the haldaemon user to the nut group
-    check_hal_in_nut_group
+    if [ -z `getent group nut | grep haldaemon` ]; then
+        adduser --quiet haldaemon nut
+    fi
     ;;
 
   abort-upgrade)
