DMF/Makefile.am : save a few cycles by only re-testing sanity of environment for DMF regeneration once (as a non-fatal prerequisite for all files)

diff --git a/scripts/DMF/Makefile.am b/scripts/DMF/Makefile.am
--- a/scripts/DMF/Makefile.am
+++ b/scripts/DMF/Makefile.am
@@ -119,20 +119,38 @@ EXTRA_DIST += $(srcdir)/gen-legacy-mibfiles-list.sh
 # generated by C preprocessor may be incompatible with pycparser and so
 # fails the build (even if the simpler tests in configure script succeeded).
 # So we specifically do not include original makefile CFLAGS below.
+
+# Note that in the current dmfify script code, the sanity checks are still
+# always done at startup. The DMFGEN_SANITY_VALIDATED helps avoid doing the
+# explicit test (or skip to avoid make-recipe fatality) for EACH file if
+# we process many at once.
+DMFGEN_SANITY_VALIDATED = $(abs_builddir)/.dmfgen-sanity-validated
+CLEAN_FILES += $(DMFGEN_SANITY_VALIDATED)
+
 if WITH_REGENERATE_DMF_SNMP
   DISTCLEANFILES += $(LEGACY_NUT_DMFS)
-  DMFGEN_DEPS += $(top_builddir)/Makefile
+  DMFGEN_DEPS += $(top_builddir)/Makefile dmfgen-sanity
   DMFGEN_CMD = ( \
-	mkdir -p $(@D) || exit ; \
-	if $(abs_srcdir)/dmfify-mib.sh --sanity-check; then \
-	    cd $(@D) && CFLAGS="$(DMFTOOLS_CFLAGS) $(AM_CFLAGS)" CPPFLAGS="$(DMFTOOLS_CPPFLAGS) $(CPPFLAGS) $(AM_CPPFLAGS)" $(abs_srcdir)/dmfify-mib.sh $< || exit; \
-	else echo "SKIP: NOT REBUILDING DMF file $@ from $< due to absence of prerequisites like Python or pycparser" >&2; \
+	mkdir -p "$(@D)" || exit ; \
+	if test -f "$(DMFGEN_SANITY_VALIDATED)" ; then \
+	    cd "$(@D)" && CFLAGS="$(DMFTOOLS_CFLAGS) $(AM_CFLAGS)" CPPFLAGS="$(DMFTOOLS_CPPFLAGS) $(CPPFLAGS) $(AM_CPPFLAGS)" $(abs_srcdir)/dmfify-mib.sh "$(<D)/$(<F)" || exit; \
 	fi; \
+	if test ! -s "$@" -a ! -s "$(abs_srcdir)/$@"; then echo "ERROR: Generated file $@ is missing" >&2; exit 2; fi; \
 	)
+
+dmfgen-sanity: $(abs_srcdir)/dmfify-mib.sh
+	@if $(abs_srcdir)/dmfify-mib.sh --sanity-check ; then \
+	    echo "Sanity-checked the low-level ability to generate DMF files - OK" >&2; \
+	    touch $(DMFGEN_SANITY_VALIDATED); \
+	else \
+	    echo "SKIP: NOT REBUILDING DMF files due to absence of prerequisites like Python or pycparser" >&2; \
+	    $(RM) $(DMFGEN_SANITY_VALIDATED); \
+	fi
 else
   EXTRA_DIST += $(dmfsnmp_DMFS)
   DMFGEN_CMD = ( \
 	echo "SKIP: Generation of $@ from $< not enabled by the configure script (--with-dmfsnmp-regenerate option)"; \
+	$(RM) $(DMFGEN_SANITY_VALIDATED); \
 	if test ! -s "$@" -a ! -s "$(abs_srcdir)/$@"; then echo "ERROR: Distributed file $@ is missing" >&2; exit 2; fi; \
 	)
 endif
