scripts/DMF/Makefile.am: revise shell script syntax with backticks and double-quotes; single-quote Make variable expansions into shell [#3196]
Signed-off-by: Jim Klimov <jimklimov+nut@gmail.com>

diff --git a/scripts/DMF/Makefile.am b/scripts/DMF/Makefile.am
--- a/scripts/DMF/Makefile.am
+++ b/scripts/DMF/Makefile.am
@@ -182,15 +182,15 @@ EXTRA_DIST += $(DMFTEST_SRC)
 # of dynamic vars, see e.g. https://man.omnios.org/man1/make#BUGS
 LINKED_SOURCE_FILES = dmfsnmp.c
 dmfsnmp.c : $(top_srcdir)/common/dmfsnmp.c
-	@test -s "$@" || ln -s -f "$(top_srcdir)/common/dmfsnmp.c" "$@"
+	@test -s '$@' || ln -s -f "$(top_srcdir)/common/dmfsnmp.c" '$@'
 
 LINKED_SOURCE_FILES += dmfcore.c
 dmfcore.c : $(top_srcdir)/common/dmfcore.c
-	@test -s "$@" || ln -s -f "$(top_srcdir)/common/dmfcore.c" "$@"
+	@test -s '$@' || ln -s -f "$(top_srcdir)/common/dmfcore.c" '$@'
 
 LINKED_SOURCE_FILES += alist.c
 alist.c : $(top_srcdir)/common/alist.c
-	@test -s "$@" || ln -s -f "$(top_srcdir)/common/alist.c" "$@"
+	@test -s '$@' || ln -s -f "$(top_srcdir)/common/alist.c" '$@'
 
 
 CLEANFILES += $(noinst_PROGRAMS) \
@@ -294,12 +294,12 @@ if WITH_REGENERATE_DMF_SNMP
 	      CPPFLAGS="$(DMFTOOLS_CPPFLAGS) $(CPPFLAGS_DMF) $(AM_CPPFLAGS)" \
 	      ABS_BUILDDIR="$(abs_builddir)" \
 	      DEBUG="$(V)" \
-	      $(abs_srcdir)/dmfify-mib.sh --skip-sanity-check "$$CMIBFILE" "$@" \
+	      $(abs_srcdir)/dmfify-mib.sh --skip-sanity-check "$$CMIBFILE" '$@' \
 	    ) || exit; \
 	fi ; \
-	if test ! -s "$@" -a ! -s "$(abs_top_builddir)/$@" -a ! -s "$(abs_top_srcdir)/$@"; then \
+	if test ! -s '$@' -a ! -s "$(abs_top_builddir)/$@" -a ! -s "$(abs_top_srcdir)/$@"; then \
 	    echo "ERROR: Generated file $@ is missing" >&2; \
-	    ls -la "$@" "$(abs_top_builddir)/$@" "$(abs_top_srcdir)/$@"; \
+	    ls -la '$@' "$(abs_top_builddir)/$@" "$(abs_top_srcdir)/$@"; \
 	    exit 2; \
 	fi; \
 	)
@@ -324,7 +324,7 @@ else !WITH_REGENERATE_DMF_SNMP
   DMFGEN_CMD = ( \
 	echo "  SKIP	Generation of $@ from $$CMIBFILE not enabled by the configure script (--with-dmfsnmp-regenerate option)"; \
 	rm -f $(DMFGEN_SANITY_VALIDATED); \
-	if test ! -s "$@" -a ! -s "$(abs_srcdir)/$@" -a ! -s "$(abs_top_builddir)/$@" -a ! -s "$(abs_top_srcdir)/$@"; then \
+	if test ! -s '$@' -a ! -s "$(abs_srcdir)/$@" -a ! -s "$(abs_top_builddir)/$@" -a ! -s "$(abs_top_srcdir)/$@"; then \
 		echo "ERROR: Distributed file $@ is missing" >&2; exit 2; \
 	fi; \
 	)
@@ -354,7 +354,7 @@ DMFLNK_CMD = ( \
 	test -f "$$DMFFILE_DIR$$DMFFILE" || { echo "`date`: 2. File '$$DMFFILE_DIR$$DMFFILE' not found yet, sleeping a bit" >&2; sleep 10 ; sync; } ; \
 	test -f "$$DMFFILE_DIR$$DMFFILE" || { echo "`date`: 3. File '$$DMFFILE_DIR$$DMFFILE' not found yet, sleeping a bit" >&2; sleep 15 ; sync; } ; \
 	if [ x"$(V)" = x1 ] ; then echo "BEFORE:" ; ls -la "$$DMFFILE_DIR$$DMFFILE" "$$DMFLINK" || true; fi ; \
-	DMFLINK_DIR="`dirname "$$DMFLINK"`"; \
+	DMFLINK_DIR="`dirname \"$$DMFLINK\"`"; \
 	test -d "$$DMFLINK_DIR" -a -w "$$DMFLINK_DIR" || $(MKDIR_P) "$$DMFLINK_DIR" || exit ; \
 	test -f "$$DMFFILE_DIR$$DMFFILE" || { echo "File '$$DMFFILE_DIR$$DMFFILE' not found" >&2; exit 22; } ; \
 	if [ x"$(V)" = x1 ] ; then echo "$(LN_S_R) '$$DMFFILE_DIR$$DMFFILE' '$$DMFLINK' || exit"; fi ; \
@@ -384,7 +384,7 @@ $(abs_builddir)/$(DMFSNMP_RES_SUBDIR)/.uptodate: $(dmfsnmpres_DMFS)
 	 else \
 		echo "INFO: Build was done out-of-tree, so will copy files from source dir if needed (if nothing got generated)"; \
 		for F in "$(abs_srcdir)/$(DMFSNMP_RES_SUBDIR)/"*.dmf ; do \
-			B="`basename "$$F"`"; \
+			B="`basename \"$$F\"`"; \
 			case "$$B" in \
 				'*.dmf') exit 0 ;; \
 				S*|K*) ;; \
@@ -397,13 +397,13 @@ $(abs_builddir)/$(DMFSNMP_RES_SUBDIR)/.uptodate: $(dmfsnmpres_DMFS)
 			esac ; \
 		done; \
 	 fi
-	touch "$@"
+	touch '$@'
 
 $(DMFSNMP_SUBDIR)/.uptodate:
 	+$(MAKE) $(AM_MAKEFLAGS) $(abs_builddir)/$(DMFSNMP_SUBDIR)/.uptodate
 
 $(abs_builddir)/$(DMFSNMP_SUBDIR)/.uptodate: $(LEGACY_NUT_DMF_SYMLINKS)
-	touch "$@"
+	touch '$@'
 
 # The recipe assumes we have separate opening and closing lines in the DMF file
 # just generated by reindexer (the "<?xml...>\n<nut>" and "</nut>" lines) and a
@@ -428,21 +428,21 @@ $(abs_top_builddir)/scripts/DMF/$(DMFNUTSCAN_RES_SUBDIR)/dmfnutscan-snmp.dmf: $(
 	  grep '<mib2nut ' "$@.tmp" | sort | uniq | grep -v 'mib_name="ietf"'; \
 	  grep '<mib2nut ' "$@.tmp" | sort | uniq | grep 'mib_name="ietf"'; \
 	  egrep -v '^$$|\<mib2nut ' "$@.tmp" | tail -1 ; \
-	) > "$@"
+	) > '$@'
 	@LANG=C; LC_ALL=C; TZ=UTC; export LANG LC_ALL TZ; \
 	  sort "$@.tmp" | egrep -v '^$$' | uniq > "$@.tmp1" ; \
-	    sort "$@" | egrep -v '^$$' | uniq > "$@.tmp2" ; \
+	    sort '$@' | egrep -v '^$$' | uniq > "$@.tmp2" ; \
 	  diff "$@.tmp1" "$@.tmp2" >/dev/null \
 	|| { echo "FAILED to sort generated $@ without losses!" >&2; \
 	     rm -f "$@.tmp"* ; exit 1; } ; exit 0
 	rm -f "$@.tmp"*
-	test -s "$@"
+	test -s '$@'
 
 else !WITH_REGENERATE_DMF_NUTSCAN
 
 $(abs_top_builddir)/scripts/DMF/$(DMFNUTSCAN_RES_SUBDIR)/dmfnutscan-snmp.dmf: $(DMFNUTSCAN_DEPS)
 	@echo "  SKIP	Generation of $@ not enabled by the configure script (--with-dmfnutscan-regenerate option)"
-	@if test ! -s "$@" -a ! -s "$(abs_srcdir)/$(DMFNUTSCAN_RES_SUBDIR)/$(@F)"; then echo "ERROR: Distributed file $@ is missing" >&2; exit 2; fi; true
+	@if test ! -s '$@' -a ! -s "$(abs_srcdir)/$(DMFNUTSCAN_RES_SUBDIR)/$(@F)"; then echo "ERROR: Distributed file $@ is missing" >&2; exit 2; fi; true
 	@test -d "$(@D)" -a -w "$(@D)" || $(MKDIR_P) "$(@D)"
 	@if [ "`cd $(abs_builddir) && pwd`" != "`cd $(abs_srcdir) && pwd`" ]; then \
 		F="$(abs_srcdir)/$(DMFNUTSCAN_RES_SUBDIR)/$(@F)"; \
@@ -453,15 +453,15 @@ $(abs_top_builddir)/scripts/DMF/$(DMFNUTSCAN_RES_SUBDIR)/dmfnutscan-snmp.dmf: $(
 			cp -f "$$F" "$$N" || { ls -la "$$F" "$$N" ; exit 1; } ; \
 		fi; \
 	 fi
-	test -s "$@"
+	test -s '$@'
 
 endif !WITH_REGENERATE_DMF_NUTSCAN
 
 $(DMFNUTSCAN_SYMLINK): $(abs_top_builddir)/scripts/DMF/$(DMFNUTSCAN_RES_SUBDIR)/dmfnutscan-snmp.dmf
-	@DMFFILE="$(DMFNUTSCAN_RES_SUBDIR)/dmfnutscan-snmp.dmf"; DMFLINK="$@"; $(DMFLNK_CMD)
+	@DMFFILE="$(DMFNUTSCAN_RES_SUBDIR)/dmfnutscan-snmp.dmf"; DMFLINK='$@'; $(DMFLNK_CMD)
 
 $(INSTALL_NUT_DMFNUTSCAN_SYMLINK): $(INSTALL_NUT_DMFNUTSCAN_FILE)
-	@DMFFILE="$(INSTALL_NUT_DMFNUTSCAN_FILE)"; DMFLINK="$@"; $(DMFLNK_CMD)
+	@DMFFILE="$(INSTALL_NUT_DMFNUTSCAN_FILE)"; DMFLINK='$@'; $(DMFLNK_CMD)
 
 $(DMFNUTSCAN_RES_SUBDIR)/.uptodate:
 	+$(MAKE) $(AM_MAKEFLAGS) $(abs_builddir)/$(DMFNUTSCAN_RES_SUBDIR)/.uptodate
@@ -469,7 +469,7 @@ $(DMFNUTSCAN_RES_SUBDIR)/.uptodate:
 $(abs_builddir)/$(DMFNUTSCAN_RES_SUBDIR)/.uptodate: $(abs_top_builddir)/scripts/DMF/$(DMFNUTSCAN_RES_SUBDIR)/dmfnutscan-snmp.dmf
 	@echo "DMFNUTSCAN_RES_SUBDIR is now up to date" >&2
 	@test -d "$(@D)" -a -w "$(@D)" || $(MKDIR_P) "$(@D)"
-	touch "$@"
+	touch '$@'
 
 $(DMFNUTSCAN_SUBDIR)/.uptodate:
 	+$(MAKE) $(AM_MAKEFLAGS) $(abs_builddir)/$(DMFNUTSCAN_SUBDIR)/.uptodate
@@ -477,7 +477,7 @@ $(DMFNUTSCAN_SUBDIR)/.uptodate:
 $(abs_builddir)/$(DMFNUTSCAN_SUBDIR)/.uptodate: $(DMFNUTSCAN_SYMLINK)
 	@echo "DMFNUTSCAN_SUBDIR is now up to date" >&2
 	@test -d "$(@D)" -a -w "$(@D)" || $(MKDIR_P) "$(@D)"
-	touch "$@"
+	touch '$@'
 
 # Validation requires xmllint, which we have if we succeed with asciidoc usage
 # TODO: Maybe per-DMF *.dmf.validated files would be better?
@@ -510,7 +510,7 @@ else !WITH_VALIDATE_DMF_SNMP
   DMFLINT_CMD = ( \
 	test -d "$(@D)" -a -w "$(@D)" || $(MKDIR_P) "$(@D)" || exit ; \
 	echo "  SKIP	Validation of $@ not enabled by the configure script ($$DMFLINT_OPTION option)" ; \
-	echo "VALIDATION-SKIPPED" > "$@" ; \
+	echo "VALIDATION-SKIPPED" > '$@' ; \
 	)
 
 endif !WITH_VALIDATE_DMF_SNMP
@@ -727,7 +727,7 @@ testdata-lua/.uptodate:
 $(abs_builddir)/testdata-lua/.uptodate: $(LUA_EXAMPLE_DMFS)
 	@echo "testdata-lua is now up to date" >&2
 	@test -d "$(@D)" -a -w "$(@D)" || $(MKDIR_P) "$(@D)"
-	touch "$@"
+	touch '$@'
 
 testdata-fun/.uptodate:
 	+$(MAKE) $(AM_MAKEFLAGS) $(abs_builddir)/testdata-fun/.uptodate
@@ -735,7 +735,7 @@ testdata-fun/.uptodate:
 $(abs_builddir)/testdata-fun/.uptodate: $(FUN_EXAMPLE_DMFS)
 	@echo "testdata-fun is now up to date" >&2
 	@test -d "$(@D)" -a -w "$(@D)" || $(MKDIR_P) "$(@D)"
-	touch "$@"
+	touch '$@'
 
 if WITH_VALIDATE_DMF_SNMP
 
@@ -745,7 +745,7 @@ $(abs_builddir)/testdata-lua/.validated: $(abs_builddir)/testdata-lua/.uptodate
 	    echo " XMLLINT-LUA  $$F"; \
 	    $(XMLLINT) --noout --schema $(abs_srcdir)/dmfsnmp.xsd "$$F" || exit; \
 	done
-	touch "$@"
+	touch '$@'
 
 $(abs_builddir)/testdata-fun/.validated: $(abs_builddir)/testdata-fun/.uptodate
 	test -d "$(@D)" -a -w "$(@D)" || $(MKDIR_P) "$(@D)"
@@ -753,14 +753,14 @@ $(abs_builddir)/testdata-fun/.validated: $(abs_builddir)/testdata-fun/.uptodate
 	    echo " XMLLINT-LUA  $$F"; \
 	    $(XMLLINT) --noout --schema $(abs_srcdir)/dmfsnmp.xsd "$$F" || exit; \
 	done
-	touch "$@"
+	touch '$@'
 
 else !WITH_VALIDATE_DMF_SNMP
 
 $(abs_builddir)/testdata-lua/.validated $(abs_builddir)/testdata-fun/.validated:
 	test -d "$(@D)" -a -w "$(@D)" || $(MKDIR_P) "$(@D)"
 	@echo "  SKIP	Validation of $@ not enabled by the configure script (--with-dmfsnmp-validate option)"
-	@echo "VALIDATION-SKIPPED" > "$@"
+	@echo "VALIDATION-SKIPPED" > '$@'
 
 endif !WITH_VALIDATE_DMF_SNMP
 
@@ -813,17 +813,17 @@ EXTRA_DIST += $(SPELLCHECK_SRC)
 # paths when parsing the other makefile (e.g. MKDIR_P that may be defined
 # via expanded $(top_builddir)/install-sh):
 #%-spellchecked: % Makefile.am $(top_srcdir)/docs/Makefile.am $(abs_srcdir)/$(NUT_SPELL_DICT)
-#       +$(MAKE) $(AM_MAKEFLAGS) -s -f $(top_builddir)/docs/Makefile MKDIR_P="$(MKDIR_P)" builddir="$(builddir)" srcdir="$(srcdir)" top_builddir="$(top_builddir)" top_srcdir="$(top_srcdir)" SPELLCHECK_SRC_ONE="$<" SPELLCHECK_SRCDIR="$(srcdir)" SPELLCHECK_BUILDDIR="$(builddir)" $@
+#       +$(MAKE) $(AM_MAKEFLAGS) -s -f $(top_builddir)/docs/Makefile MKDIR_P="$(MKDIR_P)" builddir="$(builddir)" srcdir="$(srcdir)" top_builddir="$(top_builddir)" top_srcdir="$(top_srcdir)" SPELLCHECK_SRC_ONE='$<' SPELLCHECK_SRCDIR="$(srcdir)" SPELLCHECK_BUILDDIR="$(builddir)" $@
 
 # NOTE: Portable suffix rules do not allow prerequisites, so we shim them here
 # by a wildcard target in case the make implementation can put the two together.
 *-spellchecked: Makefile.am $(top_srcdir)/docs/Makefile.am $(abs_srcdir)/$(NUT_SPELL_DICT)
 
 .sample.sample-spellchecked:
-	+$(MAKE) $(AM_MAKEFLAGS) -s -f $(top_builddir)/docs/Makefile MKDIR_P="$(MKDIR_P)" builddir="$(builddir)" srcdir="$(srcdir)" top_builddir="$(top_builddir)" top_srcdir="$(top_srcdir)" SPELLCHECK_SRC_ONE="$<" SPELLCHECK_SRCDIR="$(srcdir)" SPELLCHECK_BUILDDIR="$(builddir)" $@
+	+$(MAKE) $(AM_MAKEFLAGS) -s -f $(top_builddir)/docs/Makefile MKDIR_P="$(MKDIR_P)" builddir="$(builddir)" srcdir="$(srcdir)" top_builddir="$(top_builddir)" top_srcdir="$(top_srcdir)" SPELLCHECK_SRC_ONE='$<' SPELLCHECK_SRCDIR="$(srcdir)" SPELLCHECK_BUILDDIR="$(builddir)" $@
 
 .in.in-spellchecked:
-	+$(MAKE) $(AM_MAKEFLAGS) -s -f $(top_builddir)/docs/Makefile MKDIR_P="$(MKDIR_P)" builddir="$(builddir)" srcdir="$(srcdir)" top_builddir="$(top_builddir)" top_srcdir="$(top_srcdir)" SPELLCHECK_SRC_ONE="$<" SPELLCHECK_SRCDIR="$(srcdir)" SPELLCHECK_BUILDDIR="$(builddir)" $@
+	+$(MAKE) $(AM_MAKEFLAGS) -s -f $(top_builddir)/docs/Makefile MKDIR_P="$(MKDIR_P)" builddir="$(builddir)" srcdir="$(srcdir)" top_builddir="$(top_builddir)" top_srcdir="$(top_srcdir)" SPELLCHECK_SRC_ONE='$<' SPELLCHECK_SRCDIR="$(srcdir)" SPELLCHECK_BUILDDIR="$(builddir)" $@
 
 spellcheck spellcheck-interactive spellcheck-sortdict:
 	+$(MAKE) $(AM_MAKEFLAGS) -f $(top_builddir)/docs/Makefile MKDIR_P="$(MKDIR_P)" builddir="$(builddir)" srcdir="$(srcdir)" top_builddir="$(top_builddir)" top_srcdir="$(top_srcdir)" SPELLCHECK_SRC="$(SPELLCHECK_SRC)" SPELLCHECK_SRCDIR="$(srcdir)" SPELLCHECK_BUILDDIR="$(builddir)" $@
