scripts/DMF/Makefile.am : DMFLNK_CMD() : make sure we add symlinks to existing files

diff --git a/scripts/DMF/Makefile.am b/scripts/DMF/Makefile.am
--- a/scripts/DMF/Makefile.am
+++ b/scripts/DMF/Makefile.am
@@ -206,6 +206,7 @@ DMFLNK_CMD = ( \
 	echo "BEFORE:"; ls -la "$$DMFFILE" "$$DMFLINK" || true; \
 	DMFLINK_DIR="`dirname "$$DMFLINK"`"; \
 	test -d "$$DMFLINK_DIR" -a -w "$$DMFLINK_DIR" || $(MKDIR_P) "$$DMFLINK_DIR" || exit ; \
+	test -f "$$DMFFILE" || { echo "File '$$DMFFILE' not found"; exit 22; } ; \
 	echo "$(LN_S_R) '$$DMFFILE' '$$DMFLINK' || exit"; \
 	$(LN_S_R) "$$DMFFILE" "$$DMFLINK" || exit ; \
 	echo "AFTER:"; ls -la "$$DMFFILE" "$$DMFLINK" || true; \
