drivers/gendb: added test for gcc availability.
Fossil-ID: SVN r187

diff --git a/drivers/gendb b/drivers/gendb
--- a/drivers/gendb
+++ b/drivers/gendb
@@ -10,6 +10,12 @@
 
 MFDB=Makefile.drvbuild
 
+which gcc >& /dev/null
+if [ $? != 0 ]; then
+    echo "$0: gcc not found. Bailing out (and keeping $MFDB intact)."
+    exit 1
+fi
+
 rm -f $MFDB
 
 cat > $MFDB << EOF
@@ -51,3 +57,6 @@ for i in *.c
 do
 	gcc -I../include -MG -MM "$i" >> $MFDB
 done
+
+exit 0
+
