docs/Makefile.am, *.txt, *.adoc: Revise asciidoc markup around monospaced words
Various parsers have trouble with closing backtick followed
by a character which is not a word separator (dash seems OK,
an apostrophe precludes closing the monospace context).
Added a spellcheck-like rule to avoid regressions about this,
and fixed earlier reporting in that `docs/Makefile.am` goal.

Signed-off-by: Jim Klimov <jimklimov+nut@gmail.com>

diff --git a/docs/Makefile.am b/docs/Makefile.am
--- a/docs/Makefile.am
+++ b/docs/Makefile.am
@@ -1,6 +1,6 @@
 # Network UPS Tools: main docs
 
-# FIXME: There is a lot of shell-scripting below which gets processed by
+# NOTE: There is a lot of shell-scripting below which gets processed by
 # whatever system shell there is. While bash handles expressions like
 #   VAL="`cmd "some params"`"
 # in a way that "some params" are a single token passed to "cmd" as an
@@ -975,7 +975,11 @@ $(SPELLCHECK_BUILDDIR)/$(SPELLCHECK_SRC_ONE)-spellchecked: $(SPELLCHECK_SRCDIR)/
 		     && echo "----- ^^^" >&2 ; \
 		     exit $$RES; } ; \
 	 if $(EGREP) '^[ *.-]*(NOTE|TIP|IMPORTANT|CAUTION|WARNING):[ \t]*[a-z]' '$(SPELLCHECK_SRCDIR)/$(SPELLCHECK_SRC_ONE)' ; then \
-		echo "FAILED: Admonition block should contain a sentence, not starting with a lower-case letter" >&2 ; \
+		echo "FAILED: ASCIIDOC nuance: Admonition block should contain a sentence, not starting with a lower-case letter: '$${REPORT_PREFIX}$${REPORT_SRCDIR}$${REPORT_SRC_ONE}'" >&2 ; \
+		exit 2 ; \
+	 fi ; \
+	 if $(EGREP) '[^ \t]`'"'" '$(SPELLCHECK_SRCDIR)/$(SPELLCHECK_SRC_ONE)' ; then \
+		echo "FAILED: ASCIIDOC nuance: Closing monospace backtick should not be followed by an apostrophe, that makes it an internal backtick and keeps monospace context in place: '$${REPORT_PREFIX}$${REPORT_SRCDIR}$${REPORT_SRC_ONE}'" >&2 ; \
 		exit 2 ; \
 	 fi ; \
 	 touch '$@'
